In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
!pip install --upgrade scikit-learn

     |████████████████████████████████| 22.3 MB 1.2 MB/s 
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [ ]:

!pip install transformers
!pip install tensorboardx
!pip install simpletransformers

     |████████████████████████████████| 2.5 MB 6.1 MB/s 
     |████████████████████████████████| 3.3 MB 69.6 MB/s 
     |████████████████████████████████| 895 kB 69.9 MB/s 
     |████████████████████████████████| 124 kB 9.2 MB/s 
     |████████████████████████████████| 221 kB 8.5 MB/s 
     |████████████████████████████████| 1.8 MB 54.3 MB/s 
     |████████████████████████████████| 542 kB 95.1 MB/s 
     |████████████████████████████████| 6.6 MB 34.7 MB/s 
     |████████████████████████████████| 43 kB 2.1 MB/s 
     |████████████████████████████████| 76 kB 5.8 MB/s 
     |████████████████████████████████| 1.2 MB 33.2 MB/s 
     |████████████████████████████████| 133 kB 62.2 MB/s 
     |████████████████████████████████| 138 kB 84.6 MB/s 
     |████████████████████████████████| 170 kB 69.7 MB/s 
     |████████████████████████████████| 97 kB 8.9 MB/s 
     |████████████████████████████████| 63 kB 2.2 MB/s 
     |████████████████████████████████| 62 kB 911 kB/s 
     |█████████████████████

In [ ]:
!pip install nltk

In [ ]:
!wget aiijc.com/api_v2/task/1070/61 -O data.zip

--2021-07-21 17:48:41--  http://aiijc.com/api_v2/task/1070/61
Resolving aiijc.com (aiijc.com)... 188.93.56.95
Connecting to aiijc.com (aiijc.com)|188.93.56.95|:80... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://aiijc.com/api_v2/task/1070/61 [following]
--2021-07-21 17:48:41--  https://aiijc.com/api_v2/task/1070/61
Connecting to aiijc.com (aiijc.com)|188.93.56.95|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 891179 (870K) [application/zip]
Saving to: ‘data.zip’

data.zip            100%[===================>] 870.29K  1.25MB/s    in 0.7s    

2021-07-21 17:48:43 (1.25 MB/s) - ‘data.zip’ saved [891179/891179]



In [ ]:
!unzip -o data.zip

Archive:  data.zip
   creating: ru/
  inflating: __MACOSX/._ru           
  inflating: ru/test.csv             
  inflating: __MACOSX/ru/._test.csv  
  inflating: ru/baseline.ipynb       
  inflating: __MACOSX/ru/._baseline.ipynb  
  inflating: ru/personality.xlsx     
  inflating: __MACOSX/ru/._personality.xlsx  
  inflating: ru/target.csv           
  inflating: __MACOSX/ru/._target.csv  
  inflating: ru/train.csv            
  inflating: __MACOSX/ru/._train.csv  
  inflating: ru/sample_submission.csv  
  inflating: __MACOSX/ru/._sample_submission.csv  


In [ ]:
import pandas as pd
import numpy as np

from sklearn.svm import SVR
from sklearn.pipeline import make_pipeline
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import cross_validate
from sklearn.svm import SVC

from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, make_scorer

In [ ]:
X_train = pd.read_csv('ru/train.csv', sep=';')
X_test = pd.read_csv('ru/test.csv', sep=';')
y_train = pd.read_csv('ru/target.csv', sep=';')

In [ ]:
X_train

id                                               text
0     ID002                Добрый день, Никита. Благодарю Вас!
1     ID002  Добрый день, Элена. Я разделяю Ваше видение зн...
2     ID002       Добрый день, Герасим. Спасибо за информацию.
3     ID002                                                  -
4     ID002  Добрый день, Нелли. Оба кандидата достойные и ...
...     ...                                                ...
8949  ID220                                                  -
8950  ID220                                                  -
8951  ID220                                                  -
8952  ID220                                                  -
8953  ID220                                                  -

[8954 rows x 2 columns]

In [ ]:
y_train.info

<bound method DataFrame.info of         id  target_1  target_2  target_3  target_4  target_5  target_6
0    ID002       5.8       6.2       6.3       5.5       6.0       5.0
1    ID003       6.0       6.2       7.0       5.8       5.2       5.0
2    ID004       6.2       6.4       8.0       5.5       6.8       5.5
3    ID006       6.2       6.6       8.3       6.5       7.0       6.3
4    ID007       6.0       6.2       7.7       5.0       6.0       5.0
..     ...       ...       ...       ...       ...       ...       ...
166  ID216       5.0       5.0       5.0       5.0       4.0       4.0
167  ID217       5.0       6.0       8.0       5.0       6.0       5.0
168  ID218       5.0       5.0       6.0       4.0       6.0       5.0
169  ID219       5.0       6.0       6.0       5.0       5.0       5.0
170  ID220       5.0       5.0       6.0       5.0       5.0       6.0

[171 rows x 7 columns]>

In [ ]:
#для того, чтобы можно было задействовать регрессию
y_train['target_1'] /= 10
y_train['target_2'] /= 10
y_train['target_3'] /= 10
y_train['target_4'] /= 10
y_train['target_5'] /= 10
y_train['target_6'] /= 10

In [ ]:
y_train

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_val = train_test_split(X_train, test_size=0.2, shuffle=False)
y_train = y_train.set_index('id') 

In [ ]:
from transformers import RobertaTokenizer

# Load the BERT tokenizer.
print('Loading BERT tokenizer...')
tokenizer = RobertaTokenizer.from_pretrained('sberbank-ai/ruRoberta-large', do_lower_case=False)

Loading BERT tokenizer...


Downloading:   0%|          | 0.00/1.81M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.37M [00:00<?, ?B/s]

In [ ]:
max_len = 0

# For every sentence...
for sent in X_train['text']:
    # Tokenize the text and add `[CLS]` and `[SEP]` tokens.
    input_ids = tokenizer.encode(sent, add_special_tokens=False)
    if max_len < len(input_ids):
      print('New max_len:', len(input_ids))
    # Update the maximum sentence length. 
    max_len = max(max_len, len(input_ids))

print('Max sentence length: ', max_len)

New max_len: 9
New max_len: 97
New max_len: 125
New max_len: 135
New max_len: 144
New max_len: 208
New max_len: 227
New max_len: 293
New max_len: 332
New max_len: 667
Max sentence length:  667


In [ ]:
import torch

In [ ]:
def tokenize_sentence(text):
  encoded_dict = tokenizer.encode_plus(
                        text,                      # Sentence to encode.
                        add_special_tokens = True, # Add '[CLS]' and '[SEP]'
                        max_length = 64,           # Pad & truncate all sentences.
                        truncation = True,
                        pad_to_max_length = True,
                        return_tensors = 'pt',     # Return pytorch tensors.
                   )
  return encoded_dict['input_ids']

def tokenize_sentences(sentences_in, labels_in):
  input_ids = []
  labels = []
  for i in range(0, len(sentences_in)):
    input_id = tokenize_sentence(sentences_in[i])
    input_ids.append(input_id)
  input_ids = torch.cat(input_ids, dim=0)
  labels = torch.tensor(labels_in)
  return input_ids, labels

Model training

In [ ]:
X_train, X_val = X_train.loc[X_train['text'] != '-'], X_val.loc[X_val['text'] != '-']

In [ ]:
labels_train = list(map(lambda x: y_train.loc[x].tolist(), X_train['id']))
labels_val = list(map(lambda x: y_train.loc[x].tolist(), X_val['id']))

In [ ]:
X_train['labels'] = labels_train
X_val['labels'] = labels_val

In [ ]:
X_train

In [ ]:
X_val

In [ ]:
input_ids_train, labels_train = tokenize_sentences(X_train['text'].tolist(), labels_train)
input_ids_val, labels_val = tokenize_sentences(X_val['text'].tolist(), labels_val)

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2132: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


In [ ]:
from transformers import RobertaForSequenceClassification, AdamW, BertConfig

# Load BertForSequenceClassification, the pretrained BERT model with a single 
# linear classification layer on top. 
model = RobertaForSequenceClassification.from_pretrained(
    "sberbank-ai/ruRoberta-large", # Use the 12-layer BERT model, with an uncased vocab.
    num_labels = 6, # The number of output labels--2 for binary classification.
                    # You can increase this for multi-class tasks.   
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
)

if torch.cuda.is_available():
  # Tell pytorch to run this model on the GPU.
  model.cuda()

Downloading:   0%|          | 0.00/674 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/1.42G [00:00<?, ?B/s]

Some weights of the model checkpoint at sberbank-ai/ruRoberta-large were not used when initializing RobertaForSequenceClassification: ['lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.bias', 'lm_head.layer_norm.weight', 'lm_head.decoder.bias', 'lm_head.bias', 'lm_head.decoder.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at sberbank-ai/ruRoberta-large and are newly initialized: ['classifier.out_proj.bias', 'classifier.out

In [ ]:
from torch.utils.data import TensorDataset, random_split

train_dataset = TensorDataset(input_ids_train, labels_train)
val_dataset = TensorDataset(input_ids_val, labels_val)

In [ ]:
from torch.utils.data import DataLoader, RandomSampler, SequentialSampler

# The DataLoader needs to know our batch size for training, so we specify it 
# here. For fine-tuning BERT on a specific task, the authors recommend a batch 
# size of 16 or 32.
batch_size = 16

# Create the DataLoaders for our training and validation sets.
# We'll take training samples in random order. 
train_dataloader = DataLoader(
            train_dataset,  # The training samples.
            sampler = RandomSampler(train_dataset), # Select batches randomly
            batch_size = batch_size # Trains with this batch size.
        )

# For validation the order doesn't matter, so we'll just read them sequentially.
validation_dataloader = DataLoader(
            val_dataset, # The validation samples.
            sampler = SequentialSampler(val_dataset), # Pull out batches sequentially.
            batch_size = batch_size # Evaluate with this batch size.
        )


In [ ]:
# Note: AdamW is a class from the huggingface library (as opposed to pytorch) 
# I believe the 'W' stands for 'Weight Decay fix"
optimizer = AdamW(model.parameters(),
                  lr = 0.000001, # args.learning_rate - default is 5e-5, our notebook had 2e-5
                  eps = 1e-8 # args.adam_epsilon  - default is 1e-8.
                )


In [ ]:
from transformers import get_linear_schedule_with_warmup

# Number of training epochs. The BERT authors recommend between 2 and 4. 
# We chose to run for 4, but we'll see later that this may be over-fitting the
# training data.
epochs = 1

# Total number of training steps is [number of batches] x [number of epochs]. 
# (Note that this is not the same as the number of training samples).
total_steps = len(train_dataloader) * epochs

# Create the learning rate scheduler.
scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = 0, # Default value in run_glue.py
                                            num_training_steps = total_steps)

In [ ]:
import time
import datetime

def format_time(elapsed):
    '''
    Takes a time in seconds and returns a string hh:mm:ss
    '''
    # Round to the nearest second.
    elapsed_rounded = int(round((elapsed)))
    
    # Format as hh:mm:ss
    return str(datetime.timedelta(seconds=elapsed_rounded))


In [ ]:
import torch

# If there's a GPU available...
if torch.cuda.is_available():    

    # Tell PyTorch to use the GPU.    
    device = torch.device("cuda")

    print('There are %d GPU(s) available.' % torch.cuda.device_count())

    print('We will use the GPU:', torch.cuda.get_device_name(0))

# If not...
else:
    print('No GPU available, using the CPU instead.')
    device = torch.device("cpu")

There are 1 GPU(s) available.
We will use the GPU: Tesla P100-PCIE-16GB


In [ ]:
import random
import numpy as np
import torch
import time

# This training code is based on the `run_glue.py` script here:
# https://github.com/huggingface/transformers/blob/5bfcd0485ece086ebcbed2d008813037968a9e58/examples/run_glue.py#L128

# Set the seed value all over the place to make this reproducible.
seed_val = 42

random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)

# We'll store a number of quantities such as training and validation loss, 
# validation accuracy, and timings.
training_stats = []

# Measure the total training time for the whole run.
total_t0 = time.time()

# For each epoch...
for epoch_i in range(0, epochs):
    
    # ========================================
    #               Training
    # ========================================
    
    # Perform one full pass over the training set.

    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')

    # Measure how long the training epoch takes.
    t0 = time.time()

    # Reset the total loss for this epoch.
    total_train_loss = 0

    # Put the model into training mode. Don't be mislead--the call to 
    # `train` just changes the *mode*, it doesn't *perform* the training.
    # `dropout` and `batchnorm` layers behave differently during training
    # vs. test (source: https://stackoverflow.com/questions/51433378/what-does-model-train-do-in-pytorch)
    model.train()

    # For each batch of training data...
    for step, batch in enumerate(train_dataloader):

        # Progress update every 40 batches.
        if step % 40 == 0 and not step == 0:
            # Calculate elapsed time in minutes.
            elapsed = format_time(time.time() - t0)
            
            # Report progress.
            print('  Batch {:>5,}  of  {:>5,}.    Elapsed: {:}.'.format(step, len(train_dataloader), elapsed))

        # Unpack this training batch from our dataloader. 
        #
        # As we unpack the batch, we'll also copy each tensor to the GPU using the 
        # `to` method.
        #
        # `batch` contains three pytorch tensors:
        #   [0]: input ids 
        #   [1]: attention masks
        #   [2]: labels 
        b_input_ids = batch[0].to(device)
        b_labels = batch[1].to(device)

        # Always clear any previously calculated gradients before performing a
        # backward pass. PyTorch doesn't do this automatically because 
        # accumulating the gradients is "convenient while training RNNs". 
        # (source: https://stackoverflow.com/questions/48001598/why-do-we-need-to-call-zero-grad-in-pytorch)
        model.zero_grad()        

        # Perform a forward pass (evaluate the model on this training batch).
        # The documentation for this `model` function is here: 
        # https://huggingface.co/transformers/v2.2.0/model_doc/bert.html#transformers.BertForSequenceClassification
        # It returns different numbers of parameters depending on what arguments
        # arge given and what flags are set. For our useage here, it returns
        # the loss (because we provided labels) and the "logits"--the model
        # outputs prior to activation.
        outputs = model(b_input_ids, 
                        labels=b_labels)
        loss = outputs.loss
        logits = outputs.logits

        # Accumulate the training loss over all of the batches so that we can
        # calculate the average loss at the end. `loss` is a Tensor containing a
        # single value; the `.item()` function just returns the Python value 
        # from the tensor.
        total_train_loss += loss.item()

        # Perform a backward pass to calculate the gradients.
        loss.backward()

        # Clip the norm of the gradients to 1.0.
        # This is to help prevent the "exploding gradients" problem.
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)

        # Update parameters and take a step using the computed gradient.
        # The optimizer dictates the "update rule"--how the parameters are
        # modified based on their gradients, the learning rate, etc.
        optimizer.step()

        # Update the learning rate.
        scheduler.step()

    # Calculate the average loss over all of the batches.
    avg_train_loss = total_train_loss / len(train_dataloader)            
    
    # Measure how long this epoch took.
    training_time = format_time(time.time() - t0)

    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epcoh took: {:}".format(training_time))
        
    # ========================================
    #               Validation
    # ========================================
    # After the completion of each training epoch, measure our performance on
    # our validation set.

    print("")
    print("Running Validation...")

    t0 = time.time()

    # Put the model in evaluation mode--the dropout layers behave differently
    # during evaluation.
    model.eval()

    # Tracking variables 
    total_eval_accuracy = 0
    total_eval_loss = 0
    nb_eval_steps = 0

    # Evaluate data for one epoch
    for batch in validation_dataloader:
        
        # Unpack this training batch from our dataloader. 
        #
        # As we unpack the batch, we'll also copy each tensor to the GPU using 
        # the `to` method.
        #
        # `batch` contains three pytorch tensors:
        #   [0]: input ids 
        #   [1]: attention masks
        #   [2]: labels 
        b_input_ids = batch[0].to(device)
        b_labels = batch[1].to(device)
        
        # Tell pytorch not to bother with constructing the compute graph during
        # the forward pass, since this is only needed for backprop (training).
        with torch.no_grad():        

            # Forward pass, calculate logit predictions.
            # token_type_ids is the same as the "segment ids", which 
            # differentiates sentence 1 and 2 in 2-sentence tasks.
            # The documentation for this `model` function is here: 
            # https://huggingface.co/transformers/v2.2.0/model_doc/bert.html#transformers.BertForSequenceClassification
            # Get the "logits" output by the model. The "logits" are the output
            # values prior to applying an activation function like the softmax.
            outputs = model(b_input_ids, 
                            labels=b_labels)
            (loss, logits) = (outputs.loss, outputs.logits)
            
        # Accumulate the validation loss.
        total_eval_loss += loss.item()

        # Move logits and labels to CPU
        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()

        # Calculate the accuracy for this batch of test sentences, and
        # accumulate it over all batches.
        # total_eval_accuracy += flat_accuracy(logits, label_ids)
        

    # Report the final accuracy for this validation run.
    avg_val_accuracy = total_eval_accuracy / len(validation_dataloader)
    print("  Accuracy: {0:.2f}".format(avg_val_accuracy))

    # Calculate the average loss over all of the batches.
    avg_val_loss = total_eval_loss / len(validation_dataloader)
    
    # Measure how long the validation run took.
    validation_time = format_time(time.time() - t0)
    
    print("  Validation Loss: {0:.2f}".format(avg_val_loss))
    print("  Validation took: {:}".format(validation_time))

    # Record all statistics from this epoch.
    training_stats.append(
        {
            'epoch': epoch_i + 1,
            'Training Loss': avg_train_loss,
            'Valid. Loss': avg_val_loss,
            'Valid. Accur.': avg_val_accuracy,
            'Training Time': training_time,
            'Validation Time': validation_time
        }
    )

print("")
print("Training complete!")

print("Total training took {:} (h:mm:ss)".format(format_time(time.time()-total_t0)))


======== Epoch 1 / 1 ========
Training...
  Batch    40  of    272.    Elapsed: 0:00:16.
  Batch    80  of    272.    Elapsed: 0:00:31.
  Batch   120  of    272.    Elapsed: 0:00:47.
  Batch   160  of    272.    Elapsed: 0:01:02.
  Batch   200  of    272.    Elapsed: 0:01:17.
  Batch   240  of    272.    Elapsed: 0:01:33.

  Average training loss: 0.67
  Training epcoh took: 0:01:45

Running Validation...
  Accuracy: 0.00
  Validation Loss: 0.70
  Validation took: 0:00:07

Training complete!
Total training took 0:01:52 (h:mm:ss)


In [ ]:
print(model)

RobertaForSequenceClassification(
  (roberta): RobertaModel(
    (embeddings): RobertaEmbeddings(
      (word_embeddings): Embedding(50265, 1024, padding_idx=1)
      (position_embeddings): Embedding(514, 1024, padding_idx=1)
      (token_type_embeddings): Embedding(1, 1024)
      (LayerNorm): LayerNorm((1024,), eps=1e-05, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): RobertaEncoder(
      (layer): ModuleList(
        (0): RobertaLayer(
          (attention): RobertaAttention(
            (self): RobertaSelfAttention(
              (query): Linear(in_features=1024, out_features=1024, bias=True)
              (key): Linear(in_features=1024, out_features=1024, bias=True)
              (value): Linear(in_features=1024, out_features=1024, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): RobertaSelfOutput(
              (dense): Linear(in_features=1024, out_features=1024, bias=True)
         

Загрузка сохраненной модели


In [ ]:
from transformers import BertForSequenceClassification, AdamW, BertConfig

# import zipfile
# with zipfile.ZipFile('/content/archivedcheckpoint.zip', 'r') as zip_ref:
#     zip_ref.extractall()
model = BertForSequenceClassification.from_pretrained(
    "sberbank-ai/sbert_large_mt_nlu_ru", # Use the 12-layer BERT model, with an uncased vocab.
    num_labels = 6, # The number of output labels--2 for binary classification.
                    # You can increase this for multi-class tasks.   
    output_attentions = False, # Whether the model returns attentions weights.
    output_hidden_states = False, # Whether the model returns all hidden-states.
)
#путь к папке с моделью
model.load_state_dict(torch.load('/content/drive/MyDrive/Sber AI/checkpoint.pth'))

model.eval()

if torch.cuda.is_available():
  # Tell pytorch to run this model on the GPU.
  model.cuda()

In [ ]:
def tokenize_sentences_out(sentences_in):
  input_ids = []
  for i in range(0, len(sentences_in)):
    input_id = tokenize_sentence(sentences_in[i])
    input_ids.append(input_id)
  input_ids = torch.cat(input_ids, dim=0)
  return input_ids

In [ ]:
pred_input_ids = tokenize_sentences_out(X_val['text'].tolist())

/usr/local/lib/python3.7/dist-packages/transformers/tokenization_utils_base.py:2132: FutureWarning: The `pad_to_max_length` argument is deprecated and will be removed in a future version, use `padding=True` or `padding='longest'` to pad to the longest sequence in the batch, or use `padding='max_length'` to pad to a max length. In this case, you can give a specific length with `max_length` (e.g. `max_length=45`) or leave max_length to None to pad to the maximal input size of the model (e.g. 512 for Bert).
  FutureWarning,


In [ ]:
def predict(input_ids_in):
    model.eval()
    dataset = TensorDataset(input_ids_in)

    dataloader = DataLoader(
            dataset,  # The training samples.
            batch_size = batch_size # Trains with this batch size.
        )
    predictions = []
    for batch in dataloader:
        input_ids = batch[0].to(device)
        with torch.no_grad():
            # Forward pass, calculate logit predictions
            outputs = model(input_ids)
        
        logits = outputs[0]

        # Move logits and labels to CPU
        logits = logits.detach().cpu().numpy()
        predictions.extend(logits)
    return predictions
def predict_by_dataloader(dataloader):
    model.eval()

    predictions = []
    for batch in dataloader:
        input_ids = batch[0].to(device)
        with torch.no_grad():
            # Forward pass, calculate logit predictions
            outputs = model(input_ids)
        
        logits = outputs[0]

        # Move logits and labels to CPU
        logits = logits.detach().cpu().numpy()
        predictions.extend(logits)
    return predictions

In [ ]:
torch.cuda.empty_cache()

In [ ]:
predictions_val = predict_by_dataloader(validation_dataloader)

In [ ]:
from sklearn.metrics import mean_absolute_error as mae
from sklearn.metrics import mean_absolute_percentage_error as mape

In [ ]:
predictions_val

[array([0.31031248, 0.5469193 , 0.83191067, 0.36008334, 0.63866436,
        0.26130402], dtype=float32),
 array([0.4116755 , 0.59907526, 0.8225071 , 0.2844063 , 0.60496974,
        0.20925249], dtype=float32),
 array([0.26921165, 0.5898037 , 0.71508265, 0.2738551 , 0.5802837 ,
        0.11561378], dtype=float32),
 array([0.35289335, 0.6798512 , 0.829685  , 0.30647087, 0.59733   ,
        0.14982556], dtype=float32),
 array([0.33969986, 0.7058259 , 0.8456975 , 0.30055338, 0.6581444 ,
        0.30766106], dtype=float32),
 array([0.3768112 , 0.6267131 , 0.76822054, 0.308348  , 0.5451743 ,
        0.23933972], dtype=float32),
 array([0.41683307, 0.595418  , 0.8369149 , 0.31887856, 0.6342325 ,
        0.35421637], dtype=float32),
 array([0.40000194, 0.7733451 , 0.85910463, 0.2501313 , 0.66846454,
        0.24694023], dtype=float32),
 array([0.37831217, 0.61433434, 0.8554166 , 0.31820786, 0.63006395,
        0.28170145], dtype=float32),
 array([0.2962081 , 0.56587255, 0.7519952 , 0.349041  ,

In [ ]:
for target_num in range(6):
  print(f'MAE on {target_num + 1}:', mae(list(map(lambda x: x[target_num], X_val['labels'].tolist())), list(map(lambda x: x[target_num], predictions_val))))
  print(f'MAPE on {target_num + 1}:', mape(list(map(lambda x: x[target_num], X_val['labels'].tolist())), list(map(lambda x: x[target_num], predictions_val))))
print('MAE:', mae(X_val['labels'].tolist(), predictions_val))
print('MAPE:', mape(X_val['labels'].tolist(), predictions_val))

MAE on 1: 0.16129164800874135
MAPE on 1: 0.308074835643951
MAE on 2: 0.09054588110793388
MAPE on 2: 0.16655343907198317
MAE on 3: 0.19500246003526578
MAPE on 3: 0.367767477462491
MAE on 4: 0.1812182485259514
MAPE on 4: 0.36577777128127675
MAE on 5: 0.1282016962424747
MAPE on 5: 0.2610379827357126
MAE on 6: 0.28266877017943737
MAPE on 6: 0.5657802779715245
MAE: 0.17315478401663473
MAPE: 0.3391652973611565


In [ ]:
predictions_train = predict_by_dataloader(train_dataloader)
for target_num in range(6):
  print(f'MAE on {target_num + 1}:', mae(list(map(lambda x: x[target_num], X_train['labels'].tolist())), list(map(lambda x: x[target_num], predictions_train))))
  print(f'MAPE on {target_num + 1}:', mape(list(map(lambda x: x[target_num], X_train['labels'].tolist())), list(map(lambda x: x[target_num], predictions_train))))
print('MAE:', mae(X_train['labels'].tolist(), predictions_train))
print('MAPE:', mape(X_train['labels'].tolist(), predictions_train))

MAE on 1: 0.2300635524710415
MAPE on 1: 0.38106940902703335
MAE on 2: 0.08000366143213676
MAPE on 2: 0.12516540025331419
MAE on 3: 0.12426062142689877
MAPE on 3: 0.19496105087399254
MAE on 4: 0.26862784924783634
MAPE on 4: 0.46401902608347345
MAE on 5: 0.07693837201779084
MAPE on 5: 0.1192772805531313
MAE on 6: 0.33760471652689217
MAPE on 6: 0.6037864745303717
MAE: 0.18624979552043172
MAPE: 0.31471310688688625


Сохранение модели


In [ ]:
from google.colab import files

#сохранение модели 
torch.save(model.state_dict(), 'checkpoint.pth')
# !zip -r '/content/archivedcheckpoint.zip' '/content/checkpoint.pth'
!cp "/content/checkpoint.pth" "/content/drive/MyDrive/Sber AI" 